#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.2.1.1"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all"
     "apriltag",
    # "commands2",
     "cscore",
    # "navx"
    # "pathplannerlib"
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
     "rev",
    # "romi"
     "sim",
    # "xrp"
]

# Other pip packages to install
requires = [
     "numpy",
     "robotpy-commands-v2~=2024.2.2",
     "black==24.1.1; platform_machine != 'roborio'",
     "coverage==7.4.1; platform_machine != 'roborio'"
]

[tool.coverage.html]
directory = "coverage_html_report"

[tool.coverage.run]
branch = true
relative_files = true
